title: "Fakultät"
difficulty: 2
question: |
  Verwende eine While-Schleife, um das kleinste `n` zu finden, sodass `n! > 100_000` ist.
solution: |
  ```python
  n = 5
  faktor = 1
  for zahl in range(1, n + 1):
      faktor *= zahl
  print(f"Fakultät von {n} ist {faktor}")
  ```
