title: "Selber Testen."
difficulty: 2
question: |
  Erstelle für die folgende Funktion den docstring und gebe auch doctests an:

  ```python
  def divide(a,b):
      return float(a / b)
  ```

  Finde auch heraus, wie ein Doctest für `divide(42, 0)` angegeben werden kann, der ja
  einen `ZeroDivisionError` wirft.
solution: |
  ```python
  import doctest
  
  def divide(a, b):
      """Compute and return the quotient of two numbers.
  
      Usage examples:
      >>> divide(84, 2)
      42.0
      >>> divide(15, 3)
      5.0
      >>> divide(42, -2)
      -21.0
  
      >>> divide(42, 0)
      Traceback (most recent call last):
      ZeroDivisionError: division by zero
      """
      return float(a / b)
  
  if __name__ == '__main__':
      doctest.testmod()
  
  ```
