title: "Durchschnittsnote berechnen"
difficulty: 1
question: |
  Erstelle eine Klasse `Student`. Erzeuge eine `Student` Instanz.
  Setze bei der Instanz die Attribute `Mathenote`, `Englischnote` und `Deutschnote`.
  Schreibe dann Code, der diese Attribute ausließt und die Durchschnittsnote berechnet.

  {{ youtube_video("https://www.youtube.com/embed/wo1AvTRUIJU?si=8edJnXhyEt4t-ZEe") }}
  <pre><code>class Student:
      pass

  anna = Student()
  anna.Mathenote = 2
  anna.Englischnote = 1
  anna.Deutschnote = 1

  durchschnitt = (anna.Mathenote + anna.Englischnote + anna.Deutschnote) / 3
  print(durchschnitt)</code></pre>

  </details>
