title: "Erstelle und nutze eine virtuelle Umgebung"
difficulty: 1
question: |
  1. **Virtual Environment erstellen**: Navigiere in deinem Terminal zum Projektverzeichnis und führe `python -m venv venv_name` aus, wobei `venv_name` der Name deiner virtuellen Umgebung ist. Dies erstellt eine neue Umgebung in deinem aktuellen Verzeichnis.

  2. **Virtual Environment aktivieren**: Aktiviere die Umgebung mit dem Befehl `source {venv_name}/bin/activate`. Dieser Schritt ist notwendig, um die Umgebung in deiner aktuellen Terminal-Session zu nutzen.

     **Hinweis zu `source`**: Der Befehl `source` lädt Variablen oder Funktionen aus einer Datei in die aktuelle Session. Durch Aktivieren des Virtual Environments mittels des `activate`-Skripts werden die Umgebungsvariablen der Session temporär geändert.

  3. **Überprüfen des leeren Environments**: Mit `pip list` kannst du alle in der virtuellen Umgebung installierten Pakete auflisten. Direkt nach der Erstellung sollte nur `pip` selbst aufgelistet sein.

  <pre><code>
  Package Version
  ------- -------
  pip     24.0
  </code></pre>

  | Zum verlassen des Virtual Environment wird der Befehl `deactivate` genutzt.
