title: "jaja, das ist nützlich ohne Ende"
difficulty: 2
question: |
  Schreibe eine Klasse `StringUtil`, die diverse statische Methoden implementiert:

  * `count_words(string)` zählt die Anzahl der Wörter in einem String.
  * `count_vowels(string)` zählt die Vokale in einem String (dies kann sehr gut mit der `sum` Methode und List-Comprehension gelöst werden).
  * `is_palindrom(string)` testet, ob ein Wort ein Palindrom ist (z.B. ist `Otto` ein Palindrom, da es vorwärts und rückwärts gelesen dasselbe Wort ergibt, wenn man Groß- und Kleinschreibung ignoriert).
  * `count_substring(substring, string)` zählt, wie oft `substring` in `string` auftaucht (z.B. taucht `ana` zwei mal in `Banana` auf).

  Schreibe die Methoden und versehe zusätzlich jede mit Docstring und jeweils mindesten 3 Doctests,
  die verschiedene Anwendungen darstellen.
