services:
  web:
    build: .
    ports:
      - "8000:5000"
    restart: always
  db:
    image: "mariadb"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: testdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
