title: "Verschiedene Interpreter"
difficulty: 1
question: |
  ️
  Schaue dir das folgende Video von GK TechFlex an:

  {{ youtube_video("https://www.youtube.com/embed/vKmtwQt2uLs?si=is1Xs1t2tht_Z4Sa") }}

  Welche Pythonübersetzer gibt es und welche Vorteile haben sie bzw. warum werden sie genutzt?
solution: |
  Siehe Video in Aufgabenstellung.
