title: "Debugger bei verschachtelten if-Bedingunen"
difficulty: 2
question: |
  Kopiere den folgenden Code in eine .py Datei. Setze einen Breakpoint in der ersten Zeile.

  ```python
  a = 25
  b = 10

  if a < b:
      result = a + b
      if result > 30:
          result = result + 5
      else:
          result = result - 3
  else:
      result = a - b
      if result < 10:
          result = result * 2
      else:
          result = result // 2
  print(result)
  ```

  Sage zunächst voraus, durch welche Zeilen der Code geht. Überprüfe dies mit dem Debugger.

  Finde drei weitere belegungen von `a` und `b`, sodass insgesamt alle Zeilen mindestens ein Mal durchlaufen werden.
solution: |
  {{ youtube_video("https://www.youtube.com/embed/-HcRBSCWV-I?si=FFRzMtc-c7l3hZjZ") }}
  
  Bei der Belegungen `a = 25` und `b = 10` werden die Zeilen
  4, 11, 12, 15 und 16 durchlaufen.
  
  Um alle Fälle mindestens einmal durchzugehen, kann zum Beispiel gewählt werden:
  
  * `a = 15` und `b = 10`: Zeilen 4, 11, 12, 13, 16
  * `a = 10` und `b = 15`: Zeilen 4, 5, 6, 9, 16
  * `a = 100` und `b = 150`: Zeilen 4, 5, 6, 7, 16
