title: "Weiter mit Punkten"
difficulty: 3
question: |
  Implementiere die passende Methode, sodass die Subraktion `A - B` zweier Punkte möglich ist.

  Implementieren sie außerdem die passende Methode, um die Prüfung `A == B` durchzuführen,
  mit der man zwei Punkte auf Gleichheit prüfen kann. Zwei Punkte sind gleich,
  wenn alle Attribute (`x` und `y` übereinstimmen).

  Wenn alles richtig eingestellt wurde, müsste dieser Test funktionieren:

  ```python
  from unittest import TestCase

  class PunktTest(TestCase):

      def test_equality_0(self):
          self.assertEqual(Punkt(1, 2), Punkt(1, 2))

      def test_equality_1(self):
          self.assertNotEqual(Punkt(1, 2), Punkt(2, 1))

      def test_equality_2(self):
          self.assertNotEqual(Punkt(1, 2), (1, 2))

      def test_sub_0(self):
          a, b = Punkt(2, 1), Punkt(-1, 2)
          self.assertEqual(a - b, Punkt(3, -1))

      def test_sub_1(self):
          a = Punkt(2, 1)
          self.assertEqual(a - a, Punkt(0, 0))

      def test_sub_2(self):
          a = Punkt(2, 1)
          a -= Punkt(-1, 2)
          self.assertEqual(a, Punkt(3, -1))

      def test_sub_3(self):
          with self.assertRaises(TypeError):
              Punkt(3, 2) - 4
  ```

  {{ youtube_video("https://www.youtube.com/embed/Mk_lv8_puuE?si=qxUZPOy2Kb378q7-") }}
solution: |
  ```python
  class Punkt:
      def __init__(self, x, y):
          self.x = x
          self.y = y

      def __str__(self):
          return f"({self.x}, {self.y})"

      def __add__(self, other):
          if isinstance(other, Punkt):
              return Punkt(self.x + other.x, self.y + other.y)
          else:
              raise TypeError("Unsupported operand type. Use with another Punkt object.")

      def __eq__(self, other):
          return (isinstance(other, Punkt)
                  and self.x == other.x
                  and self.y == other.y)

      def __sub__(self, other):
          if other.isinstance(other, Punkt):
              return Punkt(self.x - other.x, self.y - other.y)
          else:
              raise TypeError("Unsupported operand type. Use with another Punkt object.")
  ```
